<?php

namespace Database\Seeders;

use App\Models\Character;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CharacterSeeder extends Seeder
{
    public function run(): void
    {
        $characters = [
            'kunna' => [
                'name' => 'KUNNA',
                'region' => 'Jawa Tengah',
                'full_name' => 'Kunna',
                'philosophy' => 'Kunanti yang di Tata',
                'height' => '178 cm',
                'weight' => '77 kg',
                'artifact' => 'Topeng',
                'power' => 'Cahaya',
                'island' => 'Jawa',
                'origin' => 'Bantul',
                'dna' => 'Raja Jawa',
                'attitude' => 'Mewakili karakter Jawa',
                'character' => 'Ramah, Santun, Sabar, Ulet, Pintar, Mengutamakan Persatuan dan Adab',
                'colors' => ['#FF6B35', '#8B4513', '#FFD700'],
                'color_names' => ['Jingga', 'Coklat Tua', 'Kuning'],
                'image' => 'characters/chara-01.png',
                'thumbnail' => 'characters/thumbnails/thumb-chara-01.png',
                'video' => 'characters/videos/patrion-kuna.mp4',
                'description' => 'KUNNA adalah karakter yang mewakili Jawa Tengah dengan filosofi "Kunanti yang di Tata". Dengan tinggi 178 cm dan berat 77 kg, KUNNA membawa artefak Topeng dan menguasai kekuatan Cahaya. Berasal dari Bantul, Jawa, KUNNA memiliki DNA Raja Jawa dan mewakili karakter Jawa yang ramah, santun, sabar, ulet, pintar, serta mengutamakan persatuan dan adab.',
                'status' => 'published',
            ],
            'wabu' => [
                'name' => 'WABU',
                'region' => 'Jakarta',
                'full_name' => 'Wabu',
                'philosophy' => 'Warisan Budaya',
                'height' => '177 cm',
                'weight' => '78 kg',
                'artifact' => 'Kode Biner',
                'power' => 'Digital',
                'island' => 'Jawa',
                'origin' => 'Jakarta',
                'dna' => 'Multi Culture (China)',
                'attitude' => 'Mewakili Karakter Betawi',
                'character' => 'Ramah, Santun, Sabar, Ulet, Pintar, Mengutamakan Persatuan dan Adab',
                'colors' => ['#FFFFFF', '#000000', '#FF0000'],
                'color_names' => ['Putih', 'Hitam', 'Merah'],
                'image' => 'characters/chara-02.png',
                'thumbnail' => 'characters/thumbnails/thumb-chara-02.png',
                'video' => 'characters/videos/patrion-wabu.mp4',
                'description' => 'WABU adalah karakter yang mewakili Jakarta dengan filosofi "Warisan Budaya". Dengan tinggi 177 cm dan berat 78 kg, WABU membawa artefak Kode Biner dan menguasai kekuatan Digital. Berasal dari Jakarta, Jawa, WABU memiliki DNA Multi Culture (China) dan mewakili karakter Betawi yang ramah, santun, sabar, ulet, pintar, serta mengutamakan persatuan dan adab.',
                'status' => 'published',
            ],
            'asta' => [
                'name' => 'ASTA',
                'region' => 'Bali',
                'full_name' => 'Asta',
                'philosophy' => 'Anak Semesta',
                'height' => '175 cm',
                'weight' => '80 kg',
                'artifact' => 'Ikat kepala',
                'power' => 'Magnet',
                'island' => 'Bali',
                'origin' => 'Bali',
                'dna' => 'Raja Bali',
                'attitude' => 'Mewakili karakter Bali',
                'character' => 'Ramah, Santun, Sabar, Ulet, Pintar, Mengutamakan Persatuan dan Adab',
                'colors' => ['#FF6B35', '#8B4513', '#FFD700'],
                'color_names' => ['Jingga', 'Coklat Tua', 'Kuning'],
                'image' => 'characters/chara-03.png',
                'thumbnail' => 'characters/thumbnails/thumb-chara-03.png',
                'video' => 'characters/videos/patrion-asta.mp4',
                'description' => 'ASTA adalah karakter yang mewakili Bali dengan filosofi "Anak Semesta". Dengan tinggi 175 cm dan berat 80 kg, ASTA membawa artefak Ikat kepala dan menguasai kekuatan Magnet. Berasal dari Bali, ASTA memiliki DNA Raja Bali dan mewakili karakter Bali yang ramah, santun, sabar, ulet, pintar, serta mengutamakan persatuan dan adab.',
                'status' => 'published',
            ],
            'taran' => [
                'name' => 'TARAN',
                'region' => 'Sumatera',
                'full_name' => 'Taran',
                'philosophy' => 'Warisan Budaya',
                'height' => '177 cm',
                'weight' => '78 kg',
                'artifact' => 'Kode Biner',
                'power' => 'Digital',
                'island' => 'Sumatera',
                'origin' => 'Bukit Tinggi',
                'dna' => 'Multi Culture (China)',
                'attitude' => 'Mewakili karakter Sumatera',
                'character' => 'Ramah, Santun, Sabar, Ulet, Pintar, Mengutamakan Persatuan dan Adab',
                'colors' => ['#FFFFFF', '#000000', '#FF0000'],
                'color_names' => ['Putih', 'Hitam', 'Merah'],
                'image' => 'characters/chara-04.png',
                'thumbnail' => 'characters/thumbnails/thumb-chara-04.png',
                'video' => 'characters/videos/patrion-taran.mp4',
                'description' => 'TARAN adalah karakter yang mewakili Sumatera dengan filosofi "Warisan Budaya". Dengan tinggi 177 cm dan berat 78 kg, TARAN membawa artefak Kode Biner dan menguasai kekuatan Digital. Berasal dari Bukit Tinggi, Sumatera, TARAN memiliki DNA Multi Culture (China) dan mewakili karakter Sumatera yang ramah, santun, sabar, ulet, pintar, serta mengutamakan persatuan dan adab.',
                'status' => 'published',
            ],
            'sanu' => [
                'name' => 'SANU',
                'region' => 'Sulawesi',
                'full_name' => 'Sanu',
                'philosophy' => 'Warisan Budaya',
                'height' => '177 cm',
                'weight' => '78 kg',
                'artifact' => 'Kode Biner',
                'power' => 'Digital',
                'island' => 'Sulawesi',
                'origin' => 'Sulawesi',
                'dna' => 'Multi Culture (China)',
                'attitude' => 'Mewakili karakter Sulawesi',
                'character' => 'Ramah, Santun, Sabar, Ulet, Pintar, Mengutamakan Persatuan dan Adab',
                'colors' => ['#FFFFFF', '#000000', '#FF0000'],
                'color_names' => ['Putih', 'Hitam', 'Merah'],
                'image' => 'characters/chara-05.png',
                'thumbnail' => 'characters/thumbnails/thumb-chara-05.png',
                'video' => 'characters/videos/patrion-sanu.mp4',
                'description' => 'SANU adalah karakter yang mewakili Sulawesi dengan filosofi "Warisan Budaya". Dengan tinggi 177 cm dan berat 78 kg, SANU membawa artefak Kode Biner dan menguasai kekuatan Digital. Berasal dari Sulawesi, SANU memiliki DNA Multi Culture (China) dan mewakili karakter Sulawesi yang ramah, santun, sabar, ulet, pintar, serta mengutamakan persatuan dan adab.',
                'status' => 'published',
            ],
            'kabi' => [
                'name' => 'KABI',
                'region' => 'Papua',
                'full_name' => 'Kabi',
                'philosophy' => 'Warisan Budaya',
                'height' => '177 cm',
                'weight' => '78 kg',
                'artifact' => 'Kode Biner',
                'power' => 'Digital',
                'island' => 'Papua',
                'origin' => 'Jayapura',
                'dna' => 'Astronesia',
                'attitude' => 'Mewakili karakter Papua',
                'character' => 'Ramah, Santun, Sabar, Ulet, Pintar, Mengutamakan Persatuan dan Adab',
                'colors' => ['#FFFFFF', '#000000', '#FF0000'],
                'color_names' => ['Putih', 'Hitam', 'Merah'],
                'image' => 'characters/chara-06.png',
                'thumbnail' => 'characters/thumbnails/thumb-chara-06.png',
                'video' => 'characters/videos/patrion-kabi.mp4',
                'description' => 'KABI adalah karakter yang mewakili Papua dengan filosofi "Warisan Budaya". Dengan tinggi 177 cm dan berat 78 kg, KABI membawa artefak Kode Biner dan menguasai kekuatan Digital. Berasal dari Jayapura, Papua, KABI memiliki DNA Astronesia dan mewakili karakter Papua yang ramah, santun, sabar, ulet, pintar, serta mengutamakan persatuan dan adab.',
                'status' => 'published',
            ],
            'arun' => [
                'name' => 'ARUN',
                'region' => 'Kalimantan',
                'full_name' => 'Arun',
                'philosophy' => 'Warisan Budaya',
                'height' => '177 cm',
                'weight' => '78 kg',
                'artifact' => 'Kode Biner',
                'power' => 'Digital',
                'island' => 'Kalimantan',
                'origin' => 'Kalimantan',
                'dna' => 'Multi Culture (China)',
                'attitude' => 'Mewakili Karakter Betawi',
                'character' => 'Ramah, Santun, Sabar, Ulet, Pintar, Mengutamakan Persatuan dan Adab',
                'colors' => ['#FFFFFF', '#000000', '#FF0000'],
                'color_names' => ['Putih', 'Hitam', 'Merah'],
                'image' => 'characters/chara-07.png',
                'thumbnail' => 'characters/thumbnails/thumb-chara-07.png',
                'video' => 'characters/videos/patrion-arun.mp4',
                'description' => 'ARUN adalah karakter yang mewakili Kalimantan dengan filosofi "Warisan Budaya". Dengan tinggi 177 cm dan berat 78 kg, ARUN membawa artefak Kode Biner dan menguasai kekuatan Digital. Berasal dari Kalimantan, ARUN memiliki DNA Multi Culture (China) dan mewakili karakter Betawi yang ramah, santun, sabar, ulet, pintar, serta mengutamakan persatuan dan adab.',
                'status' => 'published',
            ],
            'antis' => [
                'name' => 'ANTIS',
                'region' => 'Atlantis',
                'full_name' => 'Antis',
                'philosophy' => 'Warisan Budaya',
                'height' => '177 cm',
                'weight' => '78 kg',
                'artifact' => 'Kode Biner',
                'power' => 'Digital',
                'island' => 'Atlantis',
                'origin' => 'Atlantis',
                'dna' => 'Multi Culture (China)',
                'attitude' => 'Mewakili karakter Sumatera',
                'character' => 'Ramah, Santun, Sabar, Ulet, Pintar, Mengutamakan Persatuan dan Adab',
                'colors' => ['#FFFFFF', '#000000', '#FF0000'],
                'color_names' => ['Putih', 'Hitam', 'Merah'],
                'image' => 'characters/chara-08.png',
                'thumbnail' => 'characters/thumbnails/thumb-chara-08.png',
                'video' => 'characters/videos/patrion-antis.mp4',
                'description' => 'ANTIS adalah karakter yang mewakili Atlantis dengan filosofi "Warisan Budaya". Dengan tinggi 177 cm dan berat 78 kg, ANTIS membawa artefak Kode Biner dan menguasai kekuatan Digital. Berasal dari Atlantis, ANTIS memiliki DNA Multi Culture (China) dan mewakili karakter Sumatera yang ramah, santun, sabar, ulet, pintar, serta mengutamakan persatuan dan adab.',
                'status' => 'published',
            ],
        ];

        foreach ($characters as $key => $data) {
            // Check if character already exists
            $existing = Character::where('slug', $key)->first();

            if (!$existing) {
                Character::create([
                    'name' => $data['name'],
                    'slug' => $key,
                    'full_name' => $data['full_name'],
                    'region' => $data['region'],
                    'philosophy' => $data['philosophy'],
                    'height' => $data['height'],
                    'weight' => $data['weight'],
                    'artifact' => $data['artifact'],
                    'power' => $data['power'],
                    'island' => $data['island'],
                    'origin' => $data['origin'],
                    'dna' => $data['dna'],
                    'attitude' => $data['attitude'],
                    'character' => $data['character'],
                    'colors' => $data['colors'],
                    'color_names' => $data['color_names'],
                    'image' => $data['image'],
                    'thumbnail' => $data['thumbnail'],
                    'video' => $data['video'],
                    'description' => $data['description'],
                    'status' => 'draft', // Set semua karakter sebagai draft
                    'order' => $data['order'],
                ]);

                $this->command->info("Character {$data['name']} created successfully.");
            } else {
                // Update existing character
                $existing->update([
                    'full_name' => $data['full_name'],
                    'region' => $data['region'],
                    'philosophy' => $data['philosophy'],
                    'height' => $data['height'],
                    'weight' => $data['weight'],
                    'artifact' => $data['artifact'],
                    'power' => $data['power'],
                    'island' => $data['island'],
                    'origin' => $data['origin'],
                    'dna' => $data['dna'],
                    'attitude' => $data['attitude'],
                    'character' => $data['character'],
                    'colors' => $data['colors'],
                    'color_names' => $data['color_names'],
                    'image' => $data['image'],
                    'thumbnail' => $data['thumbnail'],
                    'video' => $data['video'],
                    'description' => $data['description'],
                    'order' => $data['order'],
                ]);

                $this->command->info("Character {$data['name']} updated successfully.");
            }
        }

        $this->command->info('Total characters seeded: ' . count($characters));
    }
}
